config/routes.rb
Rails.application.routes.draw do

  devise_for :users, path: '', path_names: { sign_in: 'admin', sign_out: 'logout', registration: 'register'}

  resources :consultations

  get 'about', to: 'pages#about'

  get 'mission', to: 'pages#mission'

  get 'terms', to: 'pages#terms'

  get 'privacy', to: 'pages#privacy'
  
  root to: 'pages#home'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/consultation.rb
class Consultation < ApplicationRecord
	validates_presence_of :name, :email, :phone_number, :description
	# validates :phone_number, length: { minimum: 14, maximum: 14}

end

app/models/user.rb
class User < ApplicationRecord
  ############################################################################################
  ## PeterGate Roles                                                                        ##
  ## The :user role is added by default and shouldn't be included in this list.             ##
  ## The :root_admin can access any page regardless of access settings. Use with caution!   ##
  ## The multiple option can be set to true if you need users to have multiple roles.       ##
  petergate(roles: [:admin], multiple: false)                                      ##
  ############################################################################################ 
 

  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/consultations_controller.rb
class ConsultationsController < ApplicationController
	before_action :set_consultation, only: [:destroy]
  access all: [:create, :new, :index], admin: :all

  def index
    if logged_in?(:admin)
		  @consultations = Consultation.all
    else
      redirect_to root_path, alert: "You are not authorized to view this page"
    end
	end

	def new
    @consultation = Consultation.new
  end

  def create
    @consultation = Consultation.new(consultation_params)

    respond_to do |format|
      if @consultation.save
        format.html { redirect_to new_consultation_path, notice: 'Consultation was saved, we will be in contact with you within 24 hours.' }
      else
        format.html { redirect_to new_consultation_path, alert: 'There was a problem submitting your consultation.' }
      end
    end
  end

  def destroy
    @consultation.delete
    redirect_to consultations_path, notice: 'Consultation was deleted'
  end

  private

  def consultation_params
    params.require(:consultation).permit(:name, :description, :phone_number, :email, :company_name)
  end

  def set_consultation
    @consultation = Consultation.find(params[:id])
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
  end

  def contact
  end

  def about
  end

  def privacy
  end

  def terms
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def link_fa_to(icon_name, text, link)
    link_to content_tag(:i, text, :class => "fa fa-#{icon_name} fa-icon-padding"), link
  end

  def alerts
    alert = flash[:alert]
    error = flash[:error]
    notice = flash[:notice]

    if alert
      js add_gritter(alert, title: "Geekful Thinking", sticky: false, image: :warning, time: 3000)
    elsif error
      js add_gritter(error, title: "Geekful Thinking", sticky: false, image: :error)
    else notice
      js add_gritter(notice, title: "Geekful Thinking", sticky: false, image: :success, time: 6000)
    end
    
  end
end

app/helpers/consultations_helper.rb
module ConsultationsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/consultations/_consultation_table.html.erb
<% if @consultations.any? %>
	<h3 class="text-center">Leads</h3>
		<div class="table-scroll geekful-container">
			<table class="hover stack">
		  	<thead>
		    	<tr>
			    	<th>#</th>
			      <th width="150">Date submitted</th>
			      <th width="150">Name</th>
			      <th width="200">Company Name</th>
			      <th width="200">Email</th>
			      <th width="150">Phone #</th>
			      <th width="450">Description</th>
			      <th>X</th>
		    	</tr>
		  	</thead>
			  	<% @consultations.each do |c| %>
		  	<tbody>
				    <tr id="highlight">
				    	<td>#<%= c.id %></td>
				      <td><%= c.created_at.strftime("%b %d %I:%M%P") %></td>
				      <td><%= c.name %></td>
				      <td><%= c.company_name %></td>
				      <td><%= c.email %></td>
				      <td><%= c.phone_number %></td>
				      <td><div class="table-height"><%= c.description %></div></td>
				      <td><%= link_to "", c, method: :delete, data: { confirm: "You sure?" }, class: "fa fa-trash-o fa-lg" %></td>
				    </tr>
		  	</tbody>
					<% end %>
			</table>
		</div>
<% else %>
	<h3 class="text-center">No Leads to Show</h3>
<% end %>

app/views/consultations/index.html.erb
<body class="leads" id="startchange">
	<%= render 'consultation_table' %>
</body>

app/views/consultations/new.html.erb
<body class="new-consultation" id="startchange">
  <h3 class='text-center consultation-header'>Give Us An Idea Of What You're Looking For!</h3>

  <div class='row'>
    <div class="card">
      <%= form_for @consultation do |f| %>

      <div class="card-divider small-12 medium-6 columns">
        <%= f.label :name %>
        <%= f.text_field :name, autofocus: true, placeholder: 'Name', class: 'form-text placeholder-text', required: true %>
    	</div>

      <div class="card-divider small-12 medium-6 columns">
        <%= f.label :company_name %>
        <%= f.text_field :company_name, placeholder: 'Optional', class: 'form-text placeholder-text' %>
      </div>

      <div class="card-divider small-12 medium-6 columns">
        <%= f.label :email %>
        <%= f.email_field :email, placeholder: 'Email', class: 'form-text placeholder-text', required: true %>
      </div>

      <div class="card-divider small-12 medium-6 columns" id="commentForm">
        <%= f.label :phone_number %>
        <%= f.text_field :phone_number, placeholder: 'XXX-XXX-XXXX', class: 'form-text placeholder-text', required: true, id: "phone", minlength: 14 %>
      </div>

      <div class="card-divider small-12 medium-12 columns">
        <%= f.label :description %>
        <%= f.text_area :description, placeholder: 'What can we do for you?', rows: 7, class: 'form-text placeholder-text', required: true %>
      </div>


      <div class="card-divider">
        <%= f.submit "Submit Consultation", class: 'button expanded' %>
      </div>

     <% end %>
    </div>
  </div>
<body>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Geekful Thinking</title>

    <title><%= content_for?(:title) ? yield(:title) : "Untitled" %></title>

    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
    <link href="https://fonts.googleapis.com/css?family=Oswald|Roboto|Indie+Flower" rel="stylesheet">

    <%= favicon_link_tag 'favicon/favicon.ico' %>
  </head>

  <body>
    <div class="wrapper">

      <!-- Start Top Bar -->
        <%= render 'shared/nav_head' %>
      <!-- End Top Bar -->


      <%= yield %>
    </div>

    <%= render 'shared/footer' unless controller_name == 'sessions' || controller_name == 'registrations' %>

      <%= alerts %>
  </body>
</html>

app/views/pages/_homepage_dropdown.html.erb
  <div class="row">
		<div class="row">
			<div class="small-12 medium-4 columns" data-responsive-toggle="development-design" data-hide-for=false data-smooth-scroll>
				<button class="text-center home-page-services home-button" type="button" data-toggle="development-design">
					<h4>Development</h4>
					<h4>& Design <i class="fa fa-caret-down float-right"></i></h4>
				</button>
					<div class="text-center home-page-services" id="development-design" data-animate="scale-in-up scale-out-down">
				    <p>Specializing in E-commerce for small and large businesses, along with basic web page builds. We understand the need and power of web presence, SEO, and user friendliness. Our passion for building dynamic websites will match your passion for having an amazing branding tool for your business.</p>
					</div>
			</div>

			<div class="small-12 medium-4 columns text-center"></div>

			<div class="small-12 medium-4 columns" data-responsive-toggle="media-production" data-hide-for=false>
				<button class="text-center home-page-services home-button" type="button" data-toggle="media-production">
					<h4>Media</h4> 
					<h4>Production <i class="fa fa-caret-down float-right"></i></h4>
				</button>
				<div class="text-center home-page-services" id="media-production" data-animate="scale-in-up scale-out-down">
			    <p>Want to have custom photos and videos for marketing or content on your website? Look no further, we can produce professional 4k aerial photos, 4k aerial videos, still photography, and any other type of video you may want ! Get that custom look you want to have for your site that stands out!</p>
				</div>
			</div>
	  </div>

	  <div class="row">
			<div class="small-12 medium-4 columns medium-centered text-center" data-responsive-toggle="hosting" data-hide-for=false>
				<button class="home-page-services home-button" type="button" data-toggle="hosting">
						<h4>Hosting <i class="fa fa-caret-down hosting-caret-padding"></i></h4>
				</button>
				<div class="home-page-services" id="hosting" data-animate="scale-in-up scale-out-down">
			    <p>Scratching your head when it comes to hosting and maintaining your page? Here at Geekful Thinking, we have the ability to host all of those services for you. We would maintain your website, domain, and hosting service! This will ensure fast turnaround times on any issues that may arise!</p>
				</div>
			</div>
	  </div>
	  <div class="row">
      <div class="small-12 medium-4 medium-centered columns">
          <%= link_to "Get Your Consultation Now", new_consultation_path, class: "expanded button home-page-btn" %>
      </div>
  	</div>
  </div>

app/views/pages/about.html.erb
<body class="about" id="startchange">
  <div class="about-container">
	  <div class="row align-spaced">
      <div class="small-12 medium-5 columns">
        <div class="card cody-card">
          <div class="card-section">
            <%= image_tag('https://s3-us-west-2.amazonaws.com/geekfulthinking/Cody2.jpg') %>
          </div>
          <div class="card-section cody-card-text">
            <h5>Cody Higgins, CEO</h5>
            <p>Full Stack Web Developer/Design and Business Management</p>
            <p>"The great myth of our times is that technology is communication." - Libby Larsen</p>
          </div>
        </div>
      </div>

      <div class="small-12 medium-5 columns">
        <div class="card cody-card">
          <div class="card-section">
            <%= image_tag('https://s3-us-west-2.amazonaws.com/geekfulthinking/trevorabout.jpg') %>
          </div>
          <div class="card-section cody-card-text">
            <h5>Trevor Howard, CTO</h5>
            <p>Full Stack Web Developer, API dev, and Backend Wizard</p>
            <p>"There are no traffic jams on the extra mile." - Zig Ziglar</p>
          </div>
        </div>
      </div>
    </div>
  </div>
	<div class="row text-center main-row">
	  <p>Geekful Thinking was founded by a group of people with similar ideas but a variety of backgrounds. Pulling from backgrounds in corporate call centers, local government, small business owners and the Military we are able to provide services and speak to the needs of our clients from a viewpoint that is commonly missed.</p>

	  <p>At Geekful Thinking we believe that nothing should stop you from pursuing your passions and dreams. We strive to empower small businesses and individuals worldwide. Using our skills in Media & Content Creation, Photography and Web Development we offer a variety of packages that are tailored to businesses in all stages of growth. Understanding that every client is different our packages can be adapted to your individual needs.</p> 

	  <p>If our passion matches your desire to see your dream come to life, reach out to us! We’d love to meet and go over the ways Geekful Thinking can help you.</p>

	  <p>"Life is the art of drawing without an eraser." - Unknown</p>
	</div>
</body>

app/views/pages/home.html.erb
<body class="home" id="startchange">
<%#= render 'homepage_dropdown' %>
<div class="home-button">
	<div class="row text-center">
		<div class="small-12 medium-6 large-3 columns  home-page-services" id="flippity">
			<div>
				<i class="fa fa-cube fa-5x" id="home-icon"></i>
				<h4>Development & Design</h4>
			</div>
			<p>Specializing in E-commerce for small and large businesses, along with basic web page builds. We understand the need and power of web presence, SEO, and user friendliness. Our passion for building dynamic websites will match your passion for having an amazing branding tool for your business.</p>
		</div>

		<div class="small-12 medium-6 large-3 columns  home-page-services" id="flippity2">
			<div>
				<i class="fa fa-camera-retro fa-5x" id="home-icon"></i>
				<h4>Media Production</h4>
			</div>
			<p>Want to have custom photos and videos for marketing or content on your website? Look no further, we can produce professional 4k aerial photos, 4k aerial videos, still photography, and any other type of video you may want ! Get that custom look you want to have for your site that stands out!</p>
		</div>

		<div class="small-12 medium-6 large-3 columns  home-page-services" id="flippity3">
			<div>
				<i class="fa fa-check-square-o fa-5x" id="home-icon"></i>
				<h4>Hosting</h4>
			</div>
			<p>Scratching your head when it comes to hosting and maintaining your page? Here at Geekful Thinking, we have the ability to host all of those services for you. We would maintain your website, domain, and hosting service! This will ensure fast turnaround times on any issues that may arise!</p>
		</div>

		<div class="small-12 medium-6 large-3 columns  home-page-services" id="flippity4">
			<div>
				<i class="fa fa-superpowers fa-5x" id="home-icon"></i>
				<h4>Complete Transparency</h4>
			</div>
			<p>Depending on specific requirements, we will take clients through each phase of solution development, step by step, providing sound advice on technology and application design options.</p>
		</div>
	</div>
</div>
	  <div class="row" id="consultation-now-btn">
      <div class="small-12 medium-4 medium-centered columns">
          <%= link_to "Get Your Consultation Now", new_consultation_path, class: "button home-page-btn pulse" %>
      </div>
  	</div>
</body>

app/views/pages/mission.html.erb
<body class="mission" id="startchange">
	<div class="row text-center main-row1">
	<h3>Our Social Mission</h3>
	</div>
	<div class="row text-center main-row1">
	  <p>The veteran community is one that has given so much in service to our country, yet has received so little in return. We here at Geekful Thinking aim to be part of a solution.</p>

	  <p>By providing a workspace for Veterans that have recently graduated from area Coding Bootcamps, we better prepare them for the competitive workplace that they will find themselves in. Working with our development staff on real world projects not only provides them with real world experience but also furthers the learning experience. </p>
	</div>
</body>

app/views/pages/privacy.html.erb
<body class="privacy" id="startchange">
	<div class="geekful-container text-center">
		<div class='privacy-style'>
			<div class="terms-bold">
				<h3 class="terms-bold">Privacy Policy</h3>
			</div>
			<p>Geekful Thinking does not distribute, sell or give any information to anyone at anytime concerning customers or visitors to our web site.</p>

			<p>We may collect browser platform information (what browsers are used to view our site) and screen resolution sizes using Google Analytics. We do this to determine what visitors use when accessing our web site. This helps us to advise our clientele on how large their sites should be and what applications are supported by their browsers.</p>

			<p>We do not attempt to, nor can we identify any personal information from our visitors.</p>

			<p>We do not use cookies.</p>

			<p>We do not distribute or sell email addresses to anyone at anytime.</p>

			<p>Any information given through consultation submission is at owners consent</p>
		</div>
	</div>
</body>

app/views/shared/_carousel.html.erb
<!-- <div class="orbit" role="region" aria-label="Favorite Space Pictures" data-orbit>
  <ul class="orbit-container">
    <button class="orbit-previous" aria-label="previous"><span class="show-for-sr">Previous Slide</span>&#9664;</button>
    <button class="orbit-next" aria-label="next"><span class="show-for-sr">Next Slide</span>&#9654;</button>
    <li class="orbit-slide is-active">
      <img src="assets/1.jpg" class="img-styles">
    </li>
    <li class="orbit-slide">
      <img src="assets/2.jpg" class="img-styles">
    </li>
  </ul>
</div>

  <nav class="orbit-bullets">
    <button class="is-active" data-slide="0"><span class="show-for-sr">First slide details.</span><span class="show-for-sr">Current Slide</span></button>
    <button data-slide="1"><span class="show-for-sr">Second slide details.</span></button>
    <button data-slide="2"><span class="show-for-sr">Third slide details.</span></button>
    <button data-slide="3"><span class="show-for-sr">Fourth slide details.</span></button>
  </nav> -->

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="callout large secondary">
    <div class="row">
      <div class="large-6 columns">
        <ul class="menu vertical text-center footer-menu">
          <li><h4>Geekful Thinking LLC</h4></li>
          <li>7052 S Cherry Leaf Dr, West Jordan UT, 84084</li>
        </ul>
        <div class='horizontal text-center fa-icon-padding'><strong><%= link_to "Terms", terms_path, class: "footer-links" %> | <%= link_to "Privacy", privacy_path, class: "footer-links" %> | <%= link_to "About Geekful", about_path, class: "footer-links" %></strong>
        </div>
        <ul class="menu vertical text-center footer-menu1">
          <li>&copy Geekful Thinking | 2017</li>
        </ul>
      </div>

      <div class="large-6 columns footer-contact-styles">
        <ul class="menu vertical text-center footer-menu">
          <li><h5><i class="fa fa-phone" id="footer-icon"></i><strong> (801) 879-3433</strong></h5></li>
            <li>
              <h5>
                <div class="flex-align-justify-center">
                  <i class="fa fa-envelope-o" id="footer-icon"></i>
                    <strong class="no-padding">
                      <a href="mailto:support@geekfulthinking.com?subject=Geekful Thinking Questions" "email me" id="contact-email">
                        support@geekfulthinking.com
                      </a>
                    </strong>
                </div>
              </h5>
            </li>
          <li><h4>Visit our Social Media</h4></li>
        </ul>

        <div class='horizontal text-center icon-link'>
          <%= link_fa_to 'facebook-official fa-2x', '', 'https://www.facebook.com/GeekfulThinking/' %>
          <%= link_fa_to 'linkedin-square fa-2x', '', 'https://www.linkedin.com/company-beta/18115533' %>
        </div>
      </div>

      <div class="large-6 large-centered columns text-center">
          <hr id="footer-hr">
          <div class="footer-quote">
          <strong>"No person will make a great business who wants to do it all himself or get all the credit" -Andrew Carnegie</strong>
          </div>
      </div>
    </div>
  </div>
</div>

app/views/shared/_mobile_nav.html.erb
<div class="title-bar" data-responsive-toggle="animated-menu" data-hide-for="medium">
  <div class="title-bar-title mobile-menu-text">
    <%= link_to "Geekful Thinking LLC", root_path %>    
  </div>
  <button class="fa fa-bars float-right" type="button" data-toggle="animated-menu"></button>
</div>

<!-- start of mobile nav dropdown -->
<div id="animated-menu" data-animate="hinge-in-from-top hinge-out-from-top">
  <ul class="vertical mobile-nav-links hide-for-medium">
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Social Mission", mission_path %></li>
    <li><%= link_to "Consultations", new_consultation_path %></li>
    <% if logged_in?(:admin) %>
      <li><%= link_to "Leads", consultations_path %></li>
      <li><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
    <% end %>
  </ul>
</div>
<!-- end of mobile nav dropdown-->

app/views/shared/_nav_head.html.erb
<%= render 'shared/mobile_nav' %>
<div data-sticky-container>
  <div data-sticky data-options="marginTop:0;" style="width:100%" data-top-anchor="1">
    <div class="top-bar" id="navbar-scroll">
      <div class="top-bar-left">
        <ul class="menu medium-horizontal hide-for-small-only">
          <li class="nav-logo logoslide"><%= link_to "Geekful Thinking LLC", root_path %></li>
        </ul>
      </div>
      <div class="top-bar-right">
        <ul class="menu nav-links hide-for-small-only text-right">
          <li class="navlinkhover"><%= link_to "About", about_path %></li>
          <li class="navlinkhover"><%= link_to "Social Mission", mission_path %></li>
          <li class="navlinkhover"><%= link_to "Consultations", new_consultation_path %></li>
          <% if logged_in?(:admin) %>
            <li class="navlinkhover"><%= link_to "Leads", consultations_path %></li>
            <li class="navlinkhover"><%= link_to "Logout", destroy_user_session_path, method: :delete %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</div>